
- name: Run images on hosts
  docker_container: 
    name: mongo_db
    # it could be a custom image with preconfiguration mongo
    image: " {{ mongo_image }} "
    ports: 
     - "{{ mongodb_conf_port }}": "{{ mongodb_conf_port }}"
    volumes: 
      - "{{ mongo_host_volume }}"
    env:
     - MONGO_INITDB_ROOT_USERNAME: "{{ mongodb_admin_user }}"
     - MONGO_INITDB_ROOT_PASSWORD: "{{ mongodb_admin_password }}"
